### ISSUE TITLE
Availability of the OpenAI /v1/completions API Endpoint ?

### ISSUE THREAD

**Issue by vjeantet** [bentoml/OpenLLM#1015]
Hello,

I noticed in the code examples that the OpenAI completions endpoint is implemented. Could you inform me when it will be available via the API ?

As of today, the Swagger documentation shows "v1/chat/completions" but not "v1/completions," and attempts to access the latter result in a 404 error page.

Thank you for your efforts, and keep up the good work!

Valere

**Comment by aarnphm** [comment]
Ye I can port the implementation over.

**Comment by Lexazan** [comment]
+1 for v1/completions support

**Comment by bojiang** [comment]
supported by openllm v0.6.
