### ISSUE TITLE
bug: on running openllm run <model-name>, Because vllm-flash-attn==2.5.9.post1 has no wheels with a matching Python ABI tag and you require vllm-flash-attn==2.5.9.post1, we can conclude that your requirements are unsatisfiable.

### ISSUE THREAD

**Issue by sayakmisra** [bentoml/OpenLLM#1068]
### Describe the bug

On running 
`openllm run gemma:2b`

The below error occurs 

`$ python -m uv pip install -p /home/ubuntu/.openllm/venv/397201824397438346/bin/python -r /home/ubuntu/.openllm/venv/397201824397438346/requirements.txt
  × No solution found when resolving dependencies:
  ╰─▶ Because vllm-flash-attn==2.5.9.post1 has no wheels with a matching Python ABI tag and you require vllm-flash-attn==2.5.9.post1, we can conclude that your requirements are unsatisfiable.
`

### To reproduce

1. pip install openllm
2. openllm run gemma:2b
3. below error happens
<img width="1388" alt="Screenshot 2024-08-22 at 4 39 51 PM" src="https://github.com/user-attachments/assets/d7c8bc83-d801-4851-9a70-4bd0835253d2">

### Environment

OS : Ubuntu 24.04 LTS
Python 3.12.3
openllm 0.6.10

**Comment by bojiang** [comment]
Got. vllm-flash-attn doesn't support Python3.12. Switch to 3.11 should fix it.

openllm plan to manage Python versions for users in the future. Before that we suggest users to use Python between 3.9 and 3.11, since most ml libraries support them.
