### ISSUE TITLE
run a transformers model

### ISSUE THREAD

**Issue by foxxxx001** [bentoml/OpenLLM#109]
**1.save model**
pipe = pipeline("text-generation", model="/data/Data/LLM/starchat/", torch_dtype=torch.bfloat16, device_map="auto")
bentoml.transformers.save_model(name="starsvc", pipeline=pipe)
**2.make service**
import bentoml
from bentoml.io import Text, JSON
runner = bentoml.transformers.get("starsvc").to_runner()
svc = bentoml.Service("starchat-service", runners=[runner])
@svc.api(input=Text(), output=JSON())
async def generate(input_series: str) -> list:
    return await runner.async_run(input_series)

**3.run** 
bentoml serve starsvc.py:svc

last ,I got such a error,why？

RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions

**Comment by aarnphm** [comment]
This is irelevant within OpenLLM scope, please open this issue in bentoml
