### ISSUE TITLE
feat: Specify a particular GPU for server start ?

### ISSUE THREAD

**Issue by jiapei100** [bentoml/OpenLLM#140]
### Feature request

I would like to specify which GPU I'm going to use for the model loading and start the server. How?

### Motivation

For I've got 2 GPUs. The first one is smaller, but the second one is bigger.

**Comment by QLutz** [comment]
Are you using NVIDIA GPUs? 
If that is the case, you may want to try setting the desired visible devices when running OpenLLM, e.g.:
```bash
CUDA_VISIBLE_DEVICES=0 openllm start  .... # run on GPU-0
```

**Comment by aarnphm** [comment]
We respect CUDA_VISIBLE_DEVICES, or `--device 0` should also work

Note that we also include a AMD GPU support, but ROCm is experimental. 

OpenLLM also support parsing MIG- and GPU- parsing correctly, per https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#cuda-environment-variables
