### ISSUE TITLE
Speed compares with vllm?

### ISSUE THREAD

**Issue by lucasjinreal** [bentoml/OpenLLM#172]
Speed compares with vllm?

**Comment by ehartford** [comment]
no, it does not.
https://betterprogramming.pub/frameworks-for-serving-llms-60b7f7b23407

**Comment by aarnphm** [comment]
0.2.12 adds experimental support for vLLM

**Comment by aarnphm** [comment]
We now have support for vLLM, simply use `--backend vllm` to serve model with vllm
