### ISSUE TITLE
feat: float16 support for Llama-2

### ISSUE THREAD

**Issue by geoffreyangus** [bentoml/OpenLLM#195]
### Feature request

I would like it if there was a way to convert Llama models to float16 from the openllm CLI. This might look like the following:

```
openllm start llama --model-id meta-llama/Llama-2-7b-chat-hf --torch_dtype float16
```

### Motivation

This feature would ensure that Llama-2-7B models could fit into smaller GPUs. Llama-2-7B models of dtype float16 only take up about 14GB of GPU memory.

**Comment by aarnphm** [comment]
float16 is automatically used when GPU is available
