### ISSUE TITLE
feat: screenshots, demo, how-to for openllm-ui-clojure

### ISSUE THREAD

**Issue by ehartford** [bentoml/OpenLLM#233]
### Feature request

I wanna try out openllm-ui-clojure

Can you please post screenshots, demo, and howto on running it locally?

it would be really great if there's a docker image that runs OpenLLM with a good UI.

### Motivation

easy stand up an inference engine, API and a sample UI

**Comment by aarnphm** [comment]
You can already run the LLM standalone with `ghcr.io/bentoml/openllm:0.2.25`

**Comment by ehartford** [comment]
I am want to run it locally, not in a docker container.

**Comment by aarnphm** [comment]
`hatch run ui:clojure`. The readme mention how to do it.
