### ISSUE TITLE
feat: GGML model support

### ISSUE THREAD

**Issue by matthoffner** [bentoml/OpenLLM#24]
### Feature request

Being able to use GGML models using ctransformers https://github.com/marella/ctransformers or llama.cpp https://github.com/abetlen/llama-cpp-python

### Motivation

CPU support for Starcoder and eventually Falcon models, and overall perf improvements.

**Comment by aarnphm** [comment]
I can't seem to run inference on M1 for starcoder and falcon

**Comment by matthoffner** [comment]
Starcoder works for me with ctransformers but not llama.cpp. I have some examples here: https://huggingface.co/spaces/matthoffner/starchat-ggml

Llama.cpp has great M1 support with Metal now.

Falcon is only working on a fork of ggml currently.

**Comment by aarnphm** [comment]
Got it, will look after I finish the fine-tuning API

**Comment by aarnphm** [comment]
Will track on the development of #178
