### ISSUE TITLE
bug: `openllm start chatglm --model-id` can not start an api server

### ISSUE THREAD

**Issue by zhaobu** [bentoml/OpenLLM#259]
### Describe the bug

when I execute 'openllm start chatglm --model-id ../models/Transformers/chatglm-6b/ --debug',  the model can load successful , but show '🚀 Next step: run 'openllm build chatglm' to create a Bento for chatglm' . It does not bind port 3000 to start an api server.

### To reproduce

1. openllm start chatglm --model-id ../models/Transformers/chatglm-6b/ --debug
2. openllm build chatglm --model-id ../models/Transformers/chatglm-6b/ --debug

### Logs

```shell
(gpt) liwei@lush-dev08:/data/lush-dev/liwei/code/gpt/models$ openllm start chatglm --model-id ../models/Transformers/chatglm-6b/ --debug
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:15<00:00,  1.94s/it]
Removed shared tensor {'lm_head.weight'} while saving. This should be OK, but check by verifying that you don't receive any warning while reloading
2023-08-26T09:39:06+0000 [DEBUG] [cli] Importing service "_service:svc" from working dir: "/home/liwei/miniconda3/envs/gpt/lib/python3.11/site-packages/openllm"

🚀 Next step: run 'openllm build chatglm' to create a Bento for chatglm
(gpt) liwei@lush-dev08:/data/lush-dev/liwei/code/gpt/models$ openllm build chatglm --model-id ../models/Transformers/chatglm-6b/ --debug
Building Bento for 'chatglm'
Segmentation fault (core dumped)
(gpt) liwei@lush-dev08:/data/lush-dev/liwei/code/gpt/models$
```

### Environment

 (gpt) liwei@lush-dev08:/data/lush-dev/liwei/code/gpt/models$ pip show bentoml
Name: bentoml
Version: 1.1.3
Summary: BentoML: Build Production-Grade AI Applications
Home-page: 
Author: 
Author-email: BentoML Team <contact@bentoml.com>
License: Apache-2.0
Location: /home/liwei/miniconda3/envs/gpt/lib/python3.11/site-packages
Requires: aiohttp, attrs, cattrs, circus, click, click-option-group, cloudpickle, deepmerge, fs, inflection, jinja2, numpy, opentelemetry-api, opentelemetry-instrumentation, opentelemetry-instrumentation-aiohttp-client, opentelemetry-instrumentation-asgi, opentelemetry-sdk, opentelemetry-semantic-conventions, opentelemetry-util-http, packaging, pathspec, pip-requirements-parser, pip-tools, prometheus-client, psutil, pynvml, python-dateutil, python-json-logger, python-multipart, pyyaml, requests, rich, schema, simple-di, starlette, uvicorn, watchfiles
Required-by: openllm, openllm-core
(gpt) liwei@lush-dev08:/data/lush-dev/liwei/code/gpt/models$ pip show transformers
Name: transformers
Version: 4.32.0
Summary: State-of-the-art Machine Learning for JAX, PyTorch and TensorFlow
Home-page: https://github.com/huggingface/transformers
Author: The Hugging Face team (past and future) with the help of all our contributors (https://github.com/huggingface/transformers/graphs/contributors)
Author-email: transformers@huggingface.co
License: Apache 2.0 License
Location: /home/liwei/miniconda3/envs/gpt/lib/python3.11/site-packages
Requires: filelock, huggingface-hub, numpy, packaging, pyyaml, regex, requests, safetensors, tokenizers, tqdm
Required-by: openllm, optimum
(gpt) liwei@lush-dev08:/data/lush-dev/liwei/code/gpt/models$ python -V
Python 3.11.4
(gpt) liwei@lush-dev08:/data/lush-dev/liwei/code/gpt/models$ 
(gpt) liwei@lush-dev08:/data/lush-dev/liwei/code/gpt/models$ lscpu
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   43 bits physical, 48 bits virtual
CPU(s):                          128
On-line CPU(s) list:             0-127
Thread(s) per core:              1
Core(s) per socket:              64
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       AuthenticAMD
CPU family:                      23
Model:                           49
Model name:                      AMD EPYC 7742 64-Core Processor
Stepping:                        0
Frequency boost:                 enabled
CPU MHz:                         1497.811
CPU max MHz:                     2250.0000
CPU min MHz:                     1500.0000
BogoMIPS:                        4499.90
Virtualization:                  AMD-V
L1d cache:                       4 MiB
L1i cache:                       4 MiB
L2 cache:                        64 MiB
L3 cache:                        512 MiB
NUMA node0 CPU(s):               0-63
NUMA node1 CPU(s):               64-127
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Vulnerable
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP disabled, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nop
                                 l nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_leg
                                 acy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate sme ssbd mba sev ibrs 
                                 ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm
                                 _local clzero irperf xsaveerptr wbnoinvd arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif 
                                 umip rdpid overflow_recov succor smca

**Comment by aarnphm** [comment]
Can you provide a absolute path instead of relative?

**Comment by aarnphm** [comment]
model-id is currently doesn't support relative path from parent directory, and I don't think we should support it. It seems to be a trivial feature to support, but relative is very hard to do

**Comment by aarnphm** [comment]
Please reopen once the relative path to current context path still doesn't work. Closing for now.
