### ISSUE TITLE
Document OpenLLM API

### ISSUE THREAD

**Issue by martinmr** [bentoml/OpenLLM#286]
I see this line in the README: Visit http://localhost:3000/docs.json for OpenLLM's API specification.

Can we get the documentation without having to install/run openllm? I don't have a GPU in my local machine and should not have to run the code to reference the API. I could not find the file in the repo so I assume it's built progamatically.

**Comment by martinmr** [comment]
My question is simpler, actually. If I have an openllm service running on some endpoint, which HTTP endpoint do I need to hit to send a query to that endpoint? That's the only operation I need to make, so I don't need to know the full API spec. I could wrap openllm in some bento, but that sort of defeats the purpose of directly building the bento without requiring any service code.

**Comment by aarnphm** [comment]
you can just checkout `localhost:3000` to see the endpoint. I'm working on docs atm

**Comment by martinmr** [comment]
I don't have a GPU on my local machine. Is there a way to run the server without a GPU just to check the endpoints?

**Comment by martinmr** [comment]
Nevermind, I can run a smaller model to check. I had tried a larger model and assumed all of them needed a GPU.
