### ISSUE TITLE
How to specify model id when used with bentoml?

### ISSUE THREAD

**Issue by npuichigo** [bentoml/OpenLLM#308]
I cannot find a way to specify model id after choosing model when used with bentoml, and the document doesn't mention that. Can anyone give an example for this?
```
from __future__ import annotations

import bentoml
import openllm

model = "baichuan"
llm_runner = openllm.Runner(model)

svc = bentoml.Service(name="llm-baichuan-service", runners=[llm_runner])


@svc.on_startup
def download(_: bentoml.Context):
    llm_runner.download_model()


@svc.api(input=bentoml.io.Text(), output=bentoml.io.Text())
async def prompt(input_text: str) -> str:
    answer = await llm_runner.generate.async_run(input_text)
    return answer[0]["generated_text"]
```
![image](https://github.com/bentoml/OpenLLM/assets/11533479/9711e457-f0d9-4d76-99f7-1ee3c1a46f13)
Here the environment variable mentioned [here](https://github.com/bentoml/OpenLLM/blob/8530a067ea1d189c8a860cf65b1330fed7931954/openllm-core/src/openllm_core/config/configuration_baichuan.py#L21C38-L21C104) doesn't work

**Comment by npuichigo** [comment]
`OPENLLM_MODEL_ID` works for me. The document to use `OPENLLM_Baichuan_MODEL_ID` is wrong and need to fix.

**Comment by aarnphm** [comment]
```python
runner = openllm.Runner('baichuan', model_id='...')
```

**Comment by npuichigo** [comment]
Can we enhance the document on this?

**Comment by npuichigo** [comment]
@aarnphm another question. How to pass trust_remote_code flags in the runner?

**Comment by aarnphm** [comment]
baichuan model is already have `trust_remote_code=True`

**Comment by aarnphm** [comment]
I already add an overload type for model_id, wondering why it didn't show up

**Comment by aarnphm** [comment]
For newer API, you can see an example [here](https://github.com/bentoml/OpenLLM/blob/main/examples/bentoml-demo/service.py)
