### ISSUE TITLE
bug: Unclear setup

### ISSUE THREAD

**Issue by louisfoster** [bentoml/OpenLLM#32]
### Describe the bug

Running project via README results in issues finding the necessary model. The missing step is something like `openllm download dolly-v2` before `openllm start dolly-v2` can be run.

### To reproduce

- Install per instructions
- Run per instructions

### Logs

```shell
`NotFound(bentoml.exceptions.NotFound: Model 'pt-databricks-dollyv2-3b:877db3ed12a3086500d144b9ef74e469b107a041' is not found in BentoML store`
```

### Environment

Ubuntu 22.04

**Comment by aarnphm** [comment]
Hey there, what is the version of openllm you are using?

**Comment by aarnphm** [comment]
Can you also show the output of `openllm models --show-available`?

**Comment by bharath-krishna** [comment]
Hello, I am also facing the similar issue, I ran command 
`openllm build flan-t5 --model-id google/flan-t5-large`

and it failed with error
`bentoml.exceptions.NotFound: Bento 'google-flan-t5-large-service:2d6503cbe79448e511312ba3377a9cde16a2135a' is not found in BentoML store <osfs '/home/krishnabhara01/bentoml/bentos'>`

and here is the output of `openllm models --show-available` command.
<img width="1652" alt="image" src="https://github.com/bentoml/OpenLLM/assets/7752784/50df5dbd-e141-4880-9271-0de1b9186f3e">

Please help me how to resolve this issue.

**Comment by aarnphm** [comment]
Oh sorry, this is a hindsight on my part. I will release a quick patch fix for this

**Comment by aarnphm** [comment]
Hey all, Please try out with the latest change, hopefully I have smoothen all rough edges

**Comment by aarnphm** [comment]
I have fixed this on main
