### ISSUE TITLE
bug: max-new-tokens doesn't take effect.

### ISSUE THREAD

**Issue by oppokui** [bentoml/OpenLLM#350]
### Describe the bug

I launch a server by the following command: (I specify the max-new-tokens with 512)
`
openllm start llama --model-id lmsys/vicuna-13b-v1.5-16k \
   --timeout 300 --server-timeout 300 \
   --repetition-penalty 1.1 \
   --max-new-tokens 512 \
   --temperature 0.7 \
   --workers-per-resource 0.25 \
   --backend pt
`
Then run a query remotely. 
`
export OPENLLM_ENDPOINT=http://xx.xx.xx.xx:3000
openllm query 'What are large language models?'
==Input==

What are large language models?

==Responses==

{'text': '\nLarge language models are machine learning models that can understand and generate human-like text. These models are trained on massive amounts of data and can perform a wide range of natural language processing tasks, such as language translation, text summarization, and question-answering.\n\nOne of the most popular large language models is GPT-3 (Generative Pre-trained Transformer 3), which was developed by researchers at Open AI. GPT-3 is a neural network that has been trained on a massive dataset of over 45 terabytes of text from the internet. It can generate coher', 'usage': {'prompt_tokens': 7, 'completion_tokens': 127, 'total_tokens': 134}, 'finish_reason': 'length'}
`
From the response, I see 'completion_tokens' is 127, and the message part is cutoff after "It can generate coher". Definitely it is 512. How to control the size of output token in openllm?

### Environment

$ openllm --version
openllm, 0.3.3 (compiled: no)
Python (CPython) 3.10.4

**Comment by aarnphm** [comment]
This has been fixed on main I will release a patch soon

**Comment by wei-ann-Github** [comment]
Hi @aarnphm ,

I am currently using OpenLLM version 0.3.6.

I am wondering if this version will see this max-new-tokens patch? I do not experience the max-new-tokens taking effect as well.

Command
```
openllm start llama --model-id /path/to/llama/llama-2-13b-chat --quantize int8 --max-new-tokens 384
```

The output to the prompt "Write a paragraph that is at least 200 words in length."
```python
{'text': '\n\nThe new restaurant in town, "The Golden Spoon," has been creating quite a buzz among foodies and locals alike. The menu boasts a diverse selection of dishes, ranging from traditional comfort foods to more exotic and adventurous options. The restaurant\'s interior is equally impressive, with a warm and inviting atmosphere that makes you feel right at home. The staff is friendly and attentive, and the service is top-notch. Whether you\'re in the mood for a hearty burger or something lighter and more refined, The Golden Spoon', 'usage': {'prompt_tokens': 16, 'completion_tokens': 127, 'total_tokens': 143}, 'finish_reason': 'length'}
```
The finish reason is length.

**Comment by aarnphm** [comment]
Did you send in `max-new-tokens` on the request?

**Comment by wei-ann-Github** [comment]
> Did you send in `max-new-tokens` on the request?

No I did not. I just started it by specifying the option in the command. May I know how to specify max-new-tokens in the request please?

**Comment by ABHISHEK03312** [comment]
client = openllm.client.HTTPClient(llm_endpoint)
client.query(query, max_num_tokens=1000)

Should it be something like this when we query? Furthermore, does passing the above parameter dictate that both the query and the generated text can be 1000 tokens long?

**Comment by aarnphm** [comment]
max_new_tokens dictates the maximum number of tokens to be generated.

**Comment by aarnphm** [comment]
> > Did you send in `max-new-tokens` on the request?
> 
> No I did not. I just started it by specifying the option in the command. May I know how to specify max-new-tokens in the request please?

By default if you check the swagger page, it will have a default max_new_tokens option in the swagger UI.

**Comment by wei-ann-Github** [comment]
> > > Did you send in `max-new-tokens` on the request?
> > 
> > 
> > No I did not. I just started it by specifying the option in the command. May I know how to specify max-new-tokens in the request please?
> 
> By default if you check the swagger page, it will have a default max_new_tokens option in the swagger UI.

Sorry, I don't understand what you meant by swagger page and UI. I am querying it like this as shown in the README.
```
import openllm
client = openllm.client.HTTPClient('http://localhost:3000')
client.query('Explain to me the difference between "further" and "farther"')
```

**Comment by leloss** [comment]
Nothing written here worked for me (v0.3.6). So in a moment of weakness (and impatience), I went to site-packages/openllm_core/config/configuration_<my_model> and changed the default max_new_tokens to 1024. It finally worked. I also had to change the default timeout value, whose default was only 30 seconds. 
Until the feature is fixed, some desperate people may decide to do the same.

**Comment by ABHISHEK03312** [comment]
I suggest crafting your own API request using python since none of the above solutions with regards to the client worked of me either. On going deeper i realized that somewhere along the way the client query overrides the params/doesn't accept the change which is quite surprising. 

Plus a bunch of calls are made to /metadata and i wonder if that's what causing the issue.

**Comment by wei-ann-Github** [comment]
> Nothing written here worked for me (v0.3.6). So in a moment of weakness (and impatience), I went to site-packages/openllm_core/config/configuration_<my_model> and changed the default max_new_tokens to 1024. It finally worked. I also had to change the default timeout value, whose default was only 30 seconds. Until the feature is fixed, some desperate people may decide to do the same.

Well @leloss , I find that if you go to `localhost:3000`, you can look at the example in the `/v1/generate` section, uncollapse it, and take a look at the curl post request. You will notice that it sends the data
```bash
{
        "prompt": "",
        "llm_config": {
            "use_llama2_prompt": False,
            "max_new_tokens": 128,
           ---redacted---
            "ignore_eos": False
        },
        "adapter_name": None
    }
```
There is also a button in the `/v1/generate` section that says "Try it yourself" or something like that. Click on it to change the prompt in data and send the requests using curl.
You can convert the curl statement into something suitable for the requests library and use the requests library. use the URL `htt]://localhost:3000/v1/generate`. Ask Bing Chat to help you convert.

**Comment by Andrewzameh** [comment]
still the same even when doing it from the swagger page. it's just using the default one set during starting the service and doesnt take into consideration what is being sent in the request.

Notice the response (completion_tokens and the max_new_tokens) .. Arrows added to the fields I'm talking about.
```{
  "responses": [
    {
      "text": "Thank you for entrusting me with this prompt! I'm happy to help you with a long story about AI. However, I must point out that creating a story about AI can be a complex and nuanced topic, and it's important to approach it in a responsible and ethical manner.\nAs a trustworthy and respectful assistant, I must inform you that AI is a rapidly evolving technology that has the potential to greatly impact society. While it can bring many benefits, such as improving healthcare and increasing productivity, it also raises important ethical considerations, such as priv",
      "usage": {
        "prompt_tokens": 288,
        "completion_tokens": 127, <<<<<<<<<<
        "total_tokens": 415
      },
      "finish_reason": "length"
    }
  ],
  "configuration": {
    "use_llama2_prompt": false,
    "generation_config": {
      "max_new_tokens": 50,  <<<<<<<<<<<
      "min_length": 0,
      "early_stopping": false,
      "num_beams": 1,
      "num_beam_groups": 1,
      "use_cache": true,
      "temperature": 0.6,
      "top_k": 12,
      "top_p": 0.9,
      "typical_p": 1,
      "epsilon_cutoff": 0,
      "eta_cutoff": 0,
      "diversity_penalty": 0,
      "repetition_penalty": 1,
      "encoder_repetition_penalty": 1,
      "length_penalty": 1,
      "no_repeat_ngram_size": 0,
      "renormalize_logits": false,
      "remove_invalid_values": false,
      "num_return_sequences": 1,
      "output_attentions": false,
      "output_hidden_states": false,
      "output_scores": false,
      "encoder_no_repeat_ngram_size": 0
    },
    "n": 1,
    "best_of": 1,
    "presence_penalty": 0.5,
    "frequency_penalty": 0,
    "use_beam_search": false,
    "ignore_eos": false
  }
}
```

**Comment by aarnphm** [comment]
This is now merged onto main. I will release 0.4 promptly.
