### ISSUE TITLE
bug: bash: openllm command not found

### ISSUE THREAD

**Issue by Mayurji** [bentoml/OpenLLM#385]
### Describe the bug

After installating openllm, we run 

`openllm models list`

### To reproduce

`pip install openllm`
`openllm models`

### Environment

bentoml==1.1.6
openllm==0.3.6
python==3.10.10

### System

OS: Ubuntu
Version: 20.04.6 LTS

**Comment by aarnphm** [comment]
Are you using system python or virtualenv or anything similar?

**Comment by Mayurji** [comment]
I am using Python. I've resolved this issue, openllm executable was stored in a different location unlike bentoml. After exporting the path, it worked fine.

`export PATH=$PATH:/home/<username>/.local/bin`
