### ISSUE TITLE
bug: Missing Dependency when running

### ISSUE THREAD

**Issue by IbrahimMCode** [bentoml/OpenLLM#40]
### Describe the bug

Hello,
I followed the instructions on github (nothing more) and when I try to run it with the following command:
`sudo docker run -it --rm -p 3000:3000 google-flan-t5-xl-service:53fd1e22aa944eee1fd336f9aee8a437e01676ce serve
`
I'm getting the following error.

`Error: [bentoml-cli] `serve` failed: Failed loading Bento from directory /home/bentoml/bento: Failed to import module "generated_flan_t5_service": No module named 'orjson'`

### Logs

```shell
`sudo docker run -it --rm -p 3000:3000 google-flan-t5-xl-service:53fd1e22aa944eee1fd336f9aee8a437e01676ce serve
`

`Error: [bentoml-cli] `serve` failed: Failed loading Bento from directory /home/bentoml/bento: Failed to import module "generated_flan_t5_service": No module named 'orjson'`
```

### Environment

python:3.9.17
bentoml:1.0.22
openllm:0.1.8

**Comment by aarnphm** [comment]
This is strange. Did you run into any issue when running containerize?

**Comment by aarnphm** [comment]
You shouldn't run openllm with sudo first and foremost, try again without sudo

**Comment by IbrahimMCode** [comment]
It’s not related to sudo.
Having same error without sudo

**Comment by aarnphm** [comment]
This seems like the weirdest bug to me. `orjson` is a core dependency and should already include during install openllm in the container?

Would you mind running `bentoml containerize ... --opt progress=plain` and dump all of the output to a text file and send it here? Thanks.

**Comment by aarnphm** [comment]
I discover a bug on main and I will release a new version patch version promptly

**Comment by aarnphm** [comment]
can you try with 0.1.9 to see if you still run into this issue?

**Comment by IbrahimMCode** [comment]
![image (5)](https://github.com/bentoml/OpenLLM/assets/45886749/ba13b077-a1fb-4e3b-beee-96f0cb714d4d)
Still the same issue

**Comment by IbrahimMCode** [comment]
Still the same issue.
We installed everything from scratch on another vm as well, doesn’t work

**Comment by aarnphm** [comment]
Hey there, I have identified the issue and will have a patch release soon. sorry for the trouble

**Comment by aarnphm** [comment]
Did you still run into this issue?

**Comment by MartynasZilinskas** [comment]
I was having the same error. Upgraded to latest version (`openllm, version 0.1.17`). Build step with `--overwrite` and containerize step with `--opt no-cache`. It was solved.
