### ISSUE TITLE
feat: Support changing behavior of httpx Client.

### ISSUE THREAD

**Issue by ABHISHEK03312** [bentoml/OpenLLM#409]
### Feature request

Support changing the httpx client properties for example to disable SSL verification. By default since the httpx client is loaded as part of the 'inner' class, there doesn't seem to be a way to override such parameters from the openLLM client. It requires amending OpenLLM client package source code.

### Motivation

For quick testing of the working and compatibility of the model requires leeway on such parameters.

**Comment by aarnphm** [comment]
I'm currently working on a refactoring of the client right now. Will think about this.
