### ISSUE TITLE
bug: Incorrect return type for Dolly-v2 model

### ISSUE THREAD

**Issue by ABHISHEK03312** [bentoml/OpenLLM#410]
### Describe the bug

In dolly_v2 configuration the return statement seems to be looking for the key "generated_key" in the first element of the result. However no such key exists since the returned results is a string. 

What seems to work is changing the return statement in configuration_dolly_v2.py
from -> return generation_result[0]['generated_text']
to -> return generation_result[0]

### Environment

bentoml 
openllm
requests
python=3.10

**Comment by aarnphm** [comment]
I have now unified the generation and dolly-v2 should just yield out text the same way as gpt-neox model do
