### ISSUE TITLE
feat: Query Mysql Database using english statements

### ISSUE THREAD

**Issue by FaizelK** [bentoml/OpenLLM#415]
### Feature request

It would be nice to support Database quering/agents where I could i define my database and credentials then prompt:
 "show me the last 50 records in a table and bar graph"

### Motivation

This feature would save time in designing queires and report interface and will also give user the freedom to interogate data in the way they understand and in the way they want to see it

### Other

I got this idea from using langchain sql agents, only problem is, it is not open source and has limits

**Comment by aarnphm** [comment]
I don't think this is relevant here. OpenLLM is a serving library itself, so it doesn't restrict or have any opinions wrt to downstream application.

You could definitely write an application with OpenLLM and other SQL agents.

Hope this helps
