### ISSUE TITLE
vLLM: Optimizations and AWQ

### ISSUE THREAD

**Issue by Matthieu-Tinycoaching** [bentoml/OpenLLM#416]
Hi,

Is the current release of openLLM with vLLM backend taking into account all vLLM Optimizations (Paged attention, ...) and enabling the use of AWQ quantized models?

**Comment by aarnphm** [comment]
AWQ is now supported.

If you have vllm available, you can pass in `--quantize` with `openllm start`

```bash

openllm start llama --model-id meta-llama/Llama-2-13b-chat-hf --quantize awq
```
