### ISSUE TITLE
feat: Apple M1/M2 support through MPS

### ISSUE THREAD

**Issue by ChristianWeyer** [bentoml/OpenLLM#43]
### Feature request

I want to use OpenLLM with available models to run on Apple M1/M2 processors (GPU support) through MPS.

Today:
```
openllm start falcon
No GPU available, therefore this command is disabled
```

**Comment by aarnphm** [comment]
I'm currently disabling falcon on MPS since I would just run out of memory to try even run the model on Mac

**Comment by aarnphm** [comment]
Not sure if this is valid any more. I have since tested a lot with pytorch on MPS, and it is often slower. Will probably investigate mlc vs. gguf for this.
