### ISSUE TITLE
feat: enable/disable sampling while querying model

### ISSUE THREAD

**Issue by ABHISHEK03312** [bentoml/OpenLLM#442]
### Feature request

It seems like while querying from model we don't have the leeway to enable or disable sampling as of now since the do_sample parameter throws an unknown key error while querying. 

On diving deeper into your source code I found that the do_sample is always set to true when the GenerationConfig class is called to get final LLM config for querying. 

### Motivation

For testing and downstream applications it is important to toggle this parameter at our own convenience to make way for a fair comparison between different situations that the mode is subjected to. 

As a quick fix how do I override this parameter when querying the model. 

### Other

Below is the configuration that i am using currently along with the request API that i have crafted to query the model. 

`headers = {
        'accept': 'text/event-stream',
        'Content-Type': 'application/json'
    }

data = {
    "prompt": query,
    "llm_config": {
        "use_llama2_prompt": False,
        "max_new_tokens": 2000,
        "min_length": 0,
        "early_stopping": False,
        "num_beams": 1,
        "num_beam_groups": 1,
        "use_cache": True,
        "temperature": 0.1,
        "top_k": 1,
        "top_p": 0.9,
        "typical_p": 1,
        "epsilon_cutoff": 0,
        "eta_cutoff": 0,
        "diversity_penalty": 0,
        "repetition_penalty": 1,
        "encoder_repetition_penalty": 1,
        "length_penalty": 0,
        "no_repeat_ngram_size": 0,
        "renormalize_logits": False,
        "remove_invalid_values": False,
        "num_return_sequences": 1,
        "output_attentions": False,
        "output_hidden_states": False,
        "output_scores": True,
        "encoder_no_repeat_ngram_size": 0,
        "n": 1,
        "best_of": 1,
        "presence_penalty": 0.5,
        "frequency_penalty": 0,
        "use_beam_search": False,
        "ignore_eos": False
    },
    "adapter_name": None,
}

client_conn_start = time.time()
response = requests.post(llm_endpoint, json=data, headers=headers, verify=False, stream=True, timeout=100000)
if response.status_code == 200:
    try:
        for line in response.iter_content(chunk_size=1):
                if line:
                    # print(line, end='', flush=True)
                    print(line.decode('utf-8', errors='ignore'), end='', flush=True)
    except Exception as ex: 
        print(f"Invalid chunk encoding {str(ex)}")
else:
    print(f"Error: {response.status_code} - {response.text}")`

**Comment by ABHISHEK03312** [comment]
Are there any quick fixes for this? Since i would very much like to test with the above parameter

**Comment by aarnphm** [comment]
I have rewrote the generation logic and we won't rely on `transformers.model.generate` any more.

**Comment by aarnphm** [comment]
Please try again with the latest release. Feel free to reopen if you still running into this issue.
