### ISSUE TITLE
bug: Docs shows blank pages

### ISSUE THREAD

**Issue by ABHISHEK03312** [bentoml/OpenLLM#444]
### Describe the bug

There is nothing other than blank pages shown in the docs. I exactly followed the steps to clone and install the necessary packages using pnpm. However, after starting the server it just shows a blank page at all the endpoints. 

I wonder if the docs were kept as a placeholder and still in the process of development.  

### Environment

node version 18.18.0
npm version 9.8.1

**Comment by aarnphm** [comment]
The docs is still working in progress. I haven't finished it yet.
