### ISSUE TITLE
feat: Support for Mistral models

### ISSUE THREAD

**Issue by bilelomrani1** [bentoml/OpenLLM#446]
### Feature request

Adding support for the Mistral architecture to OpenLLM.

### Motivation

The recently released Mistral 7B model is claimed to match the performance of Llama 2 13B, which makes it a very interesting base model in practical use cases. Adding support for the Mistral architecture would be a very nice addition to OpenLLM.

**Comment by aarnphm** [comment]
This is now included on main and will be released in 0.4
