### ISSUE TITLE
load a model from local path

### ISSUE THREAD

**Issue by foxxxx001** [bentoml/OpenLLM#46]
when I load my local mode with model-id ,It fails,How can I do ?"Invalid value for '--model-id': '/disk/model/glm6b2' is not one of 'thudm/chatglm-6b', 'thudm/chatglm-6b-int8', 'thudm/chatglm-6b-int4'."

**Comment by aarnphm** [comment]
That seems to be a bug, let me make a PR for that.

**Comment by aarnphm** [comment]
Hi there, this has been addressed on main. I'm thinking of doing a release today.

**Comment by aarnphm** [comment]
I have released the latest version to address this. Thanks for posting this
