### ISSUE TITLE
bug: OpenLLM not working in langchain

### ISSUE THREAD

**Issue by Rehan-shah** [bentoml/OpenLLM#48]
### Describe the bug

OpenLLM not working in langchain in google colab doc

### To reproduce

https://colab.research.google.com/drive/11awO0MyCeh0Yi88EoPY_4LBs8IfiN0Iu?usp=sharing

### Environment

google colab

**Comment by bmwas** [comment]
Looks like the langchain integrations had not been merged ---> see https://github.com/hwchase17/langchain/pull/6578 but a pull request was approved this morning, therefore hopefully will be available with the next release of langchain.

**Comment by aarnphm** [comment]
Versiono 0.0.209 has included langchain integration
