### ISSUE TITLE
feat: Support chatglm2-6b-32k

### ISSUE THREAD

**Issue by yinggoga** [bentoml/OpenLLM#512]
### Feature request

The chatglm2-6b-32k is just released, please consider supporting it: https://huggingface.co/THUDM/chatglm2-6b-32k

Thanks!

**Comment by aarnphm** [comment]
This is now supported with vllm built from main, and OpenLLM on main.

You can try the nightly wheels from OpenLLM as well as building vllm from source for now.

Once vLLM release a new version I will make a new patch version for openllm.
