### ISSUE TITLE
output "killed" with nothing else

### ISSUE THREAD

**Issue by Songjc0511** [bentoml/OpenLLM#543]
![Screenshot from 2023-10-30 17-15-38](https://github.com/bentoml/OpenLLM/assets/108270936/a8413a19-6174-4bc0-a245-612db7b7fc5f)
I tried use OpenLLM with my merged Llama model, and it print two lines of  "Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.", and then, KILLED.

Then I used just llama model, and it just print KILLED 

is anything I did wrong?

**Comment by Songjc0511** [comment]
python 3.9
cuda 11.8

**Comment by aarnphm** [comment]
what version of openllm is this?

**Comment by bojiang** [comment]
close for openllm 0.6
