### ISSUE TITLE
feat: change port number

### ISSUE THREAD

**Issue by japri** [bentoml/OpenLLM#547]
### Feature request

how to change port number from default 3000

### Motivation

i need to solve the port confilcting in my system.

**Comment by aarnphm** [comment]
You can alreaady change this with `--port`. All `bentoml serve` arguments are passed directly to `openllm start`

**Comment by japri** [comment]
hi, thanks, i try it and it works to change the port using this command openllm start opt --port 3333

but unfortunately when i open in browser something wrong. with this error message:


```
Failed to open a WebSocket connection: invalid Connection header: keep-alive.

You cannot access a WebSocket server directly with a browser. You need a WebSocket client.
```
