### ISSUE TITLE
bug: Is Baichuan2 model supported?

### ISSUE THREAD

**Issue by ozmemory** [bentoml/OpenLLM#666]
### Describe the bug

I tried to load Baichuan2-13B-Chat model but failed with exception.
I wonder if it's supported or I have to config it somehow.

### To reproduce

Run
`TRUST_REMOTE_CODE=True openllm start /localdirectory/Baichuan2-13B-Chat`

### Logs

```shell
Given model is a local model, OpenLLM will load model into memory for serialisation.
Traceback (most recent call last):
  File "/home/test/.conda/envs/openllm/lib/python3.10/site-packages/openllm/_llm.py", line 232, $
n __init__
    model = bentoml.models.get(self.tag)
  File "/home/test/.conda/envs/openllm/lib/python3.10/site-packages/simple_di/__init__.py", line
139, in _
    return func(*_inject_args(bind.args), **_inject_kwargs(bind.kwargs))
  File "/home/test/.conda/envs/openllm/lib/python3.10/site-packages/bentoml/models.py", line 45,
in get
    return _model_store.get(tag)
  File "/home/test/.conda/envs/openllm/lib/python3.10/site-packages/bentoml/_internal/store.py",
line 158, in get
    raise NotFound(
bentoml.exceptions.NotFound: Model 'pt-baichuan2-13b-chat:db4bdfbae79c96fd2d1bea907848e71371047459$
 is not found in BentoML store <osfs '/home/test/bentoml/models'>, you may need to run `bentoml $
odels pull` first
```

### Environment

**bentoml env result:**
#### Environment variable

```bash
BENTOML_DEBUG=''
BENTOML_QUIET=''
BENTOML_BUNDLE_LOCAL_BUILD=''
BENTOML_DO_NOT_TRACK=''
BENTOML_CONFIG=''
BENTOML_CONFIG_OPTIONS=''
BENTOML_PORT=''
BENTOML_HOST=''
BENTOML_API_WORKERS=''
```

#### System information

`bentoml`: 1.1.9
`python`: 3.10.13
`platform`: Linux-4.15.0-212-generic-x86_64-with-glibc2.27
`uid_gid`: 1005:1004
`conda`: 22.9.0
`in_conda_env`: True
<details><summary><code>conda_packages</code></summary>

<br>

```yaml
name: openllm
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.08.22=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.12=h7f8727e_0
  - pip=23.3=py310h06a4308_0
  - python=3.10.13=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - setuptools=68.0.0=py310h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.41.2=py310h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
    - accelerate==0.24.1
    - aiohttp==3.8.6
    - aiosignal==1.3.1
    - anyio==4.0.0
    - appdirs==1.4.4
    - asgiref==3.7.2
    - async-timeout==4.0.3
    - attrs==23.1.0
    - auto-gptq==0.5.1+cu118
    - bentoml==1.1.9
    - bitsandbytes==0.41.2.post2
    - build==0.10.0
    - cattrs==23.1.2
    - certifi==2023.7.22
    - charset-normalizer==3.3.2
    - circus==0.18.0
    - click==8.1.7
    - click-option-group==0.5.6
    - cloudpickle==3.0.0
    - cmake==3.27.7
    - coloredlogs==15.0.1
    - contextlib2==21.6.0
    - cpm-kernels==1.0.11
    - cuda-python==12.3.0
    - datasets==2.14.6
    - deepmerge==1.1.0
    - deprecated==1.2.14
    - dill==0.3.7
    - distlib==0.3.7
    - distro==1.8.0
    - exceptiongroup==1.1.3
    - fastcore==1.5.29
    - filelock==3.13.1
    - filetype==1.2.0
    - frozenlist==1.4.0
    - fs==2.4.16
    - fsspec==2023.10.0
    - gekko==1.0.6
    - ghapi==1.0.4
    - h11==0.14.0
    - httpcore==1.0.2
    - httpx==0.25.1
    - huggingface-hub==0.17.3
    - humanfriendly==10.0
    - idna==3.4
    - importlib-metadata==6.8.0
    - inflection==0.5.1
    - jinja2==3.1.2
    - lit==17.0.5
    - markdown-it-py==3.0.0
    - markupsafe==2.1.3
    - mdurl==0.1.2
    - mpmath==1.3.0
    - multidict==6.0.4
    - multiprocess==0.70.15
    - mypy-extensions==1.0.0
    - networkx==3.2.1
    - numpy==1.26.2
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu11==11.7.101
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu11==8.5.0.96
    - nvidia-cudnn-cu12==8.9.2.26
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu11==10.2.10.91
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu11==11.4.0.1
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu11==11.7.4.91
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-ml-py==11.525.150
    - nvidia-nccl-cu11==2.14.3
    - nvidia-nccl-cu12==2.18.1
    - nvidia-nvjitlink-cu12==12.3.52
    - nvidia-nvtx-cu11==11.7.91
    - nvidia-nvtx-cu12==12.1.105
    - openllm==0.4.9
    - openllm-client==0.4.9
    - openllm-core==0.4.9
    - opentelemetry-api==1.20.0
    - opentelemetry-instrumentation==0.41b0
    - opentelemetry-instrumentation-aiohttp-client==0.41b0
    - opentelemetry-instrumentation-asgi==0.41b0
    - opentelemetry-sdk==1.20.0
    - opentelemetry-semantic-conventions==0.41b0
    - opentelemetry-util-http==0.41b0
    - optimum==1.14.1
    - orjson==3.9.10
    - packaging==23.2
    - pandas==2.1.3
    - pathspec==0.11.2
    - peft==0.6.2
    - pillow==10.1.0
    - pip-requirements-parser==32.0.1
    - pip-tools==7.3.0
    - platformdirs==3.11.0
    - prometheus-client==0.18.0
    - protobuf==4.25.0
    - psutil==5.9.6
    - pyarrow==14.0.1
    - pydantic==1.10.13
    - pygments==2.16.1
    - pyparsing==3.1.1
    - pyproject-hooks==1.0.0
    - pysocks==1.7.1
    - python-dateutil==2.8.2
    - python-json-logger==2.0.7
    - python-multipart==0.0.6
    - pytz==2023.3.post1
    - pyyaml==6.0.1
    - pyzmq==25.1.1
    - regex==2023.10.3
    - requests==2.31.0
    - rich==13.6.0
    - rouge==1.0.1
    - safetensors==0.4.0
    - schema==0.7.5
    - scipy==1.11.3
    - sentencepiece==0.1.99
    - simple-di==0.1.5
    - six==1.16.0
    - sniffio==1.3.0
    - starlette==0.32.0.post1
    - sympy==1.12
    - tokenizers==0.13.3
    - tomli==2.0.1
    - torch==2.0.1
    - tornado==6.3.3
    - tqdm==4.66.1
    - transformers==4.33.1
    - triton==2.0.0
    - typing-extensions==4.8.0
    - tzdata==2023.3
    - urllib3==2.1.0
    - uvicorn==0.24.0.post1
    - virtualenv==20.24.6
    - watchfiles==0.21.0
    - wrapt==1.16.0
    - xxhash==3.4.1
    - yarl==1.9.2
    - zipp==3.17.0
prefix: /home/test/.conda/envs/openllm
```

</details>

<details><summary><code>pip_packages</code></summary>

<br>

```
accelerate==0.24.1
aiohttp==3.8.6
aiosignal==1.3.1
anyio==4.0.0
appdirs==1.4.4
asgiref==3.7.2
async-timeout==4.0.3
attrs==23.1.0
auto-gptq==0.5.1+cu118
bentoml==1.1.9
bitsandbytes==0.41.2.post2
build==0.10.0
cattrs==23.1.2
certifi==2023.7.22
charset-normalizer==3.3.2
circus==0.18.0
click==8.1.7
click-option-group==0.5.6
cloudpickle==3.0.0
cmake==3.27.7
coloredlogs==15.0.1
contextlib2==21.6.0
cpm-kernels==1.0.11
cuda-python==12.3.0
datasets==2.14.6
deepmerge==1.1.0
Deprecated==1.2.14
dill==0.3.7
distlib==0.3.7
distro==1.8.0
exceptiongroup==1.1.3
fastcore==1.5.29
filelock==3.13.1
filetype==1.2.0
frozenlist==1.4.0
fs==2.4.16
fsspec==2023.10.0
gekko==1.0.6
ghapi==1.0.4
h11==0.14.0
httpcore==1.0.2
httpx==0.25.1
huggingface-hub==0.17.3
humanfriendly==10.0
idna==3.4
importlib-metadata==6.8.0
inflection==0.5.1
Jinja2==3.1.2
lit==17.0.5
markdown-it-py==3.0.0
MarkupSafe==2.1.3
mdurl==0.1.2
mpmath==1.3.0
multidict==6.0.4
multiprocess==0.70.15
mypy-extensions==1.0.0
networkx==3.2.1
numpy==1.26.2
nvidia-cublas-cu11==11.10.3.66
nvidia-cublas-cu12==12.1.3.1
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-cupti-cu12==12.1.105
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-nvrtc-cu12==12.1.105
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cuda-runtime-cu12==12.1.105
nvidia-cudnn-cu11==8.5.0.96
nvidia-cudnn-cu12==8.9.2.26
nvidia-cufft-cu11==10.9.0.58
nvidia-cufft-cu12==11.0.2.54
nvidia-curand-cu11==10.2.10.91
nvidia-curand-cu12==10.3.2.106
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusolver-cu12==11.4.5.107
nvidia-cusparse-cu11==11.7.4.91
nvidia-cusparse-cu12==12.1.0.106
nvidia-ml-py==11.525.150
nvidia-nccl-cu11==2.14.3
nvidia-nccl-cu12==2.18.1
nvidia-nvjitlink-cu12==12.3.52
nvidia-nvtx-cu11==11.7.91
nvidia-nvtx-cu12==12.1.105
openllm==0.4.9
openllm-client==0.4.9
openllm-core==0.4.9
opentelemetry-api==1.20.0
opentelemetry-instrumentation==0.41b0
opentelemetry-instrumentation-aiohttp-client==0.41b0
opentelemetry-instrumentation-asgi==0.41b0
opentelemetry-sdk==1.20.0
opentelemetry-semantic-conventions==0.41b0
opentelemetry-util-http==0.41b0
optimum==1.14.1
orjson==3.9.10
packaging==23.2
pandas==2.1.3
pathspec==0.11.2
peft==0.6.2
Pillow==10.1.0
pip-requirements-parser==32.0.1
pip-tools==7.3.0
platformdirs==3.11.0
prometheus-client==0.18.0
protobuf==4.25.0
psutil==5.9.6
pyarrow==14.0.1
pydantic==1.10.13
Pygments==2.16.1
pyparsing==3.1.1
pyproject_hooks==1.0.0
PySocks==1.7.1
python-dateutil==2.8.2
python-json-logger==2.0.7
python-multipart==0.0.6
pytz==2023.3.post1
PyYAML==6.0.1
pyzmq==25.1.1
regex==2023.10.3
requests==2.31.0
rich==13.6.0
rouge==1.0.1
safetensors==0.4.0
schema==0.7.5
scipy==1.11.3
sentencepiece==0.1.99
simple-di==0.1.5
six==1.16.0
sniffio==1.3.0
starlette==0.32.0.post1
sympy==1.12
tokenizers==0.13.3
tomli==2.0.1
torch==2.0.1
tornado==6.3.3
tqdm==4.66.1
transformers==4.33.1
triton==2.0.0
typing_extensions==4.8.0
tzdata==2023.3
urllib3==2.1.0
uvicorn==0.24.0.post1
virtualenv==20.24.6
watchfiles==0.21.0
wrapt==1.16.0
xxhash==3.4.1
yarl==1.9.2
zipp==3.17.0
```

</details>

**transformers-cli env result:**
- `transformers` version: 4.33.1
- Platform: Linux-4.15.0-212-generic-x86_64-with-glibc2.27
- Python version: 3.10.13
- Huggingface_hub version: 0.17.3
- Safetensors version: 0.4.0
- Accelerate version: 0.24.1
- Accelerate config:    not found
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <True>
- Using distributed or parallel set-up in script?: <False>

**Comment by aarnphm** [comment]
What version of openllm is this?

**Comment by ozmemory** [comment]
> What version of openllm is this?这是什么版本的openllm？

OpenLLM 0.4.9

**Comment by d4munche3z** [comment]
I have the same issue but with another model
openllm start /home/munche3z/PycharmProjects/devteam/deepseek-coder-33B-instruct-AWQ --quantize awq --backend vllm --workers-per-resource conserved --max-model-len 16384 --serialisation safetensors --dtype float16 --temperature 0.85 --device all --debug
'--quantize=awq' might not work with 'safetensors' serialisation format.
Make sure to check out '/home/munche3z/PycharmProjects/devteam/deepseek-coder-33B-instruct-AWQ' repository to see if the weights is in 'safetensors' format if unsure.
Tip: You can always fallback to '--serialisation legacy' when running quantisation.
Tip: You can always fallback to '--serialisation legacy' when running quantisation.
Given model is a local model, OpenLLM will load model into memory for serialisation.
Traceback (most recent call last):
  File "/home/munche3z/miniconda3/envs/devteam/lib/python3.10/site-packages/openllm/_llm.py", line 227, in __init__
    model = bentoml.models.get(self.tag)
  File "/home/munche3z/miniconda3/envs/devteam/lib/python3.10/site-packages/simple_di/__init__.py", line 139, in _
    return func(*_inject_args(bind.args), **_inject_kwargs(bind.kwargs))
  File "/home/munche3z/miniconda3/envs/devteam/lib/python3.10/site-packages/bentoml/models.py", line 45, in get
    return _model_store.get(tag)
  File "/home/munche3z/miniconda3/envs/devteam/lib/python3.10/site-packages/bentoml/_internal/store.py", line 158, in get
    raise NotFound(
bentoml.exceptions.NotFound: Model 'vllm-deepseek-coder-33b-instruct-awq:014ab8a9f8c4e4808bc3093e7783f005e0269b26' is not found in BentoML store <osfs '/home/munche3z/bentoml/models'>, you may need to run `bentoml models pull` first

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/munche3z/miniconda3/envs/devteam/bin/openllm", line 8, in <module>
    sys.exit(cli())
  File "/home/munche3z/miniconda3/envs/devteam/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/munche3z/miniconda3/envs/devteam/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/munche3z/miniconda3/envs/devteam/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/munche3z/miniconda3/envs/devteam/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/munche3z/miniconda3/envs/devteam/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/munche3z/miniconda3/envs/devteam/lib/python3.10/site-packages/openllm_cli/entrypoint.py", line 229, in wrapper
    return_value = func(*args, **attrs)
  File "/home/munche3z/miniconda3/envs/devteam/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/munche3z/miniconda3/envs/devteam/lib/python3.10/site-packages/openllm_cli/entrypoint.py", line 208, in wrapper
    return f(*args, **attrs)
  File "/home/munche3z/miniconda3/envs/devteam/lib/python3.10/site-packages/openllm_cli/entrypoint.py", line 436, in start_command
    llm = openllm.LLM[t.Any, t.Any](
  File "/home/munche3z/miniconda3/envs/devteam/lib/python3.10/typing.py", line 957, in __call__
    result = self.__origin__(*args, **kwargs)
  File "/home/munche3z/miniconda3/envs/devteam/lib/python3.10/site-packages/openllm/_llm.py", line 229, in __init__
    model = openllm.serialisation.import_model(self, trust_remote_code=self.trust_remote_code)
  File "/home/munche3z/miniconda3/envs/devteam/lib/python3.10/site-packages/openllm/serialisation/__init__.py", line 78, in caller
    return getattr(importlib.import_module(f'.{serde}', 'openllm.serialisation'), fn)(llm, *args, **kwargs)
  File "/home/munche3z/miniconda3/envs/devteam/lib/python3.10/site-packages/openllm/serialisation/transformers/__init__.py", line 46, in import_model
    model = infer_autoclass_from_llm(llm, config).from_pretrained(
  File "/home/munche3z/miniconda3/envs/devteam/lib/python3.10/site-packages/openllm/serialisation/transformers/_helpers.py", line 40, in infer_autoclass_from_llm
    raise ValueError(
ValueError: Invalid configuration for /home/munche3z/PycharmProjects/devteam/deepseek-coder-33B-instruct-AWQ. ``trust_remote_code=True`` requires `transformers.PretrainedConfig` to contain a `auto_map` mapping

**Comment by aarnphm** [comment]
I will support baichuan2 onwards, and have dropped baichuan 1 for now. Releasing 0.4.28 for this.
