### ISSUE TITLE
feat: disable GPU (or at least VRAM)

### ISSUE THREAD

**Issue by AdamKnube** [bentoml/OpenLLM#67]
### Feature request

I have CUDA libs installed and run out of VRAM:
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 1.95 GiB total capacity; 1.72 GiB already allocated;

My video card is an old (cheap) one and this is to be expected. Is there a way (runtime/config flag) to use system RAM instead of video RAM?
Even if it means disabling GPU support completely, I'm fine with that. 

Perhaps something along the lines of: --novram or --nogpu
Cheers.

### Motivation

I'd like to keep my CUDA libraries installed for other projects and an option would allow this.

**Comment by aarnphm** [comment]
YOu can know disable CUDA via `CUDA_VISIBLE_DEVICES`

**Comment by redet-G** [comment]
That is you can run the following command to set it empty
```
export CUDA_VISIBLE_DEVICES=
