### ISSUE TITLE
feat: Expose vllm max-model-len parameter to avoid OOM issues with AWQ quantized models using vllm

### ISSUE THREAD

**Issue by muc-martin** [bentoml/OpenLLM#696]
### Feature request

I get CUDA OOM errors when using vllm on AWQ quantized models (7B on RTX3090), to avoid this I have to set the max-model-len parameter to 4096. (also see this: [https://github.com/vllm-project/vllm/issues/1234](https://github.com/vllm-project/vllm/issues/1234)).

Could you expose this parameter also in openllm?

Currently a workaround is to go into the config.json of the model:

~/bentoml/models/vllm-thebloke--zephyr-7b-beta-awq/ad7867b7a09d5504c86cc015d2d3a73904d488dd

and set max_position_embeddings to 4096 (which was previously set to 32768.

### Motivation

running awq quantized models in openllm

**Comment by aarnphm** [comment]
This is now supported on main with `--max-model-len`
