### ISSUE TITLE
bug: Failed to run on specified gpus

### ISSUE THREAD

**Issue by giangnguyen2412** [bentoml/OpenLLM#737]
### Describe the bug

When I run

> openllm start NousResearch/llama-2-7b-hf --device 6

I got:

> if err != cuda.CUresult.CUDA_SUCCESS: raise ValueError(f'Failed to get device {el}')
ValueError: Failed to get device 6

It seems that the code could not parse the device.

Any device other than 0 or 1 will get the same error than above.

### To reproduce

N/A

### Logs

```shell
N/A
```

### Environment

N/A

### System information (Optional)

N/A

**Comment by aarnphm** [comment]
Do you have 6 GPUS?

I will check this

**Comment by giangnguyen2412** [comment]
Hi Aaron,

Yes, I have 8 GPUS indexed from 0-7. 0-5 are now being occupied and I am trying to run

> openllm start --device 6 facebook/opt-1.3b

or 

> openllm start --device 7 facebook/opt-1.3b

but it failed all the time as I got:

> File "/home/giang/anaconda3/envs/kNN/lib/python3.9/site-packages/openllm/_strategies.py", line 152, in validate
if err != cuda.CUresult.CUDA_SUCCESS: raise ValueError(f'Failed to get device {el}')
ValueError: Failed to get device 6

**Comment by giangnguyen2412** [comment]
@aarnphm any updates on this?

**Comment by TobiasIlicic** [comment]
[aarnphm](https://github.com/aarnphm) Im having the same problem, any updates on this?

**Comment by EddyJensR** [comment]
Same here, in my case I have 4 80GB GPUs; It runs fine in card 0; but in card 2 it fails (That is a problem when I'm trying to use very large LLMs, that use more than a single GPU)

**Comment by bojiang** [comment]
close for openllm 0.6
