### ISSUE TITLE
bug: Model is not found in BentoML store, you may need to run bentoml models pull first

### ISSUE THREAD

**Issue by jim1997** [bentoml/OpenLLM#755]
### Describe the bug

I cannot run my predownloaded Baichuan-13B-Chat-4bits model successfully, it said the model is not found in BentoML store <osfs '/root/bentoml/models'>, you may need to run `bentoml models pull` first.
/root/bentoml/models this file was empty.Could anyone tell how to fix this problem?

### To reproduce
pip install "openllm[baichuan]"

TRUST_REMOTE_CODE=True openllm start baichuan-inc/Baichuan2-13B-Chat-4bits --backend vllm
### Logs

```shell
root@a8ee5a6d1333:/Baichuan2-13B# TRUST_REMOTE_CODE=True openllm start baichuan-inc/Baichuan2-13B-Chat-4bits --backend vllm
Given model is a local model, OpenLLM will load model into memory for serialisation.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/openllm/_llm.py", line 198, in __init__
    model = bentoml.models.get(self.tag)
  File "/usr/local/lib/python3.8/dist-packages/simple_di/__init__.py", line 139, in _
    return func(*_inject_args(bind.args), **_inject_kwargs(bind.kwargs))
  File "/usr/local/lib/python3.8/dist-packages/bentoml/models.py", line 45, in get
    return _model_store.get(tag)
  File "/usr/local/lib/python3.8/dist-packages/bentoml/_internal/store.py", line 158, in get
    raise NotFound(
bentoml.exceptions.NotFound: Model 'vllm-baichuan2-13b-chat-4bits:d8312ff4e0a1e3c24a9864265abfaf4250d8ba39' is not found in BentoML store <osfs '/root/bentoml/models'>, you may need to run `bentoml models pull` first

```

### Environment

accelerate==0.24.1
aiohttp==3.9.1
aioprometheus==23.3.0
aiosignal==1.3.1
altair==5.1.2
anyio==3.7.1
appdirs==1.4.4
asgiref==3.7.2
async-timeout==4.0.3
attrs==23.1.0
backports.zoneinfo==0.2.1
bentoml==1.1.10
bitsandbytes==0.41.1
blinker==1.7.0
build==0.10.0
cachetools==5.3.2
cattrs==23.1.2
certifi==2023.7.22
charset-normalizer==3.3.2
circus==0.18.0
click==8.1.7
click-option-group==0.5.6
cloudpickle==3.0.0
cmake==3.27.7
colorama==0.4.6
coloredlogs==15.0.1
contextlib2==21.6.0
cpm-kernels==1.0.11
cuda-python==12.3.0
datasets==2.14.7
deepmerge==1.1.0
Deprecated==1.2.14
dill==0.3.7
distlib==0.3.7
distro==1.8.0
einops==0.7.0
exceptiongroup==1.2.0
fastapi==0.104.1
fastcore==1.5.29
filelock==3.13.1
filetype==1.2.0
frozenlist==1.4.0
fs==2.4.16
fsspec==2023.10.0
ghapi==1.0.4
gitdb==4.0.11
GitPython==3.1.40
h11==0.14.0
httpcore==1.0.2
httptools==0.6.1
httpx==0.25.2
huggingface-hub==0.17.3
humanfriendly==10.0
idna==3.4
importlib-metadata==6.8.0
importlib-resources==6.1.1
inflection==0.5.1
Jinja2==3.1.2
jsonschema==4.19.2
jsonschema-specifications==2023.7.1
lit==17.0.4
markdown-it-py==3.0.0
MarkupSafe==2.1.3
mdurl==0.1.2
mpmath==1.3.0
msgpack==1.0.7
multidict==6.0.4
multiprocess==0.70.15
mypy-extensions==1.0.0
networkx==3.1
ninja==1.11.1.1
numpy==1.24.4
nvidia-cublas-cu12==12.1.3.1
nvidia-cuda-cupti-cu12==12.1.105
nvidia-cuda-nvrtc-cu12==12.1.105
nvidia-cuda-runtime-cu12==12.1.105
nvidia-cudnn-cu12==8.9.2.26
nvidia-cufft-cu12==11.0.2.54
nvidia-curand-cu12==10.3.2.106
nvidia-cusolver-cu12==11.4.5.107
nvidia-cusparse-cu12==12.1.0.106
nvidia-ml-py==11.525.150
nvidia-nccl-cu12==2.18.1
nvidia-nvjitlink-cu12==12.3.101
nvidia-nvtx-cu12==12.1.105
openllm==0.4.34
openllm-client==0.4.34
openllm-core==0.4.34
opentelemetry-api==1.20.0
opentelemetry-instrumentation==0.41b0
opentelemetry-instrumentation-aiohttp-client==0.41b0
opentelemetry-instrumentation-asgi==0.41b0
opentelemetry-sdk==1.20.0
opentelemetry-semantic-conventions==0.41b0
opentelemetry-util-http==0.41b0
optimum==1.14.1
orjson==3.9.10
packaging==23.2
pandas==2.0.3
pathspec==0.11.2
Pillow==10.1.0
pip-requirements-parser==32.0.1
pip-tools==7.3.0
pkgutil_resolve_name==1.3.10
platformdirs==4.0.0
prometheus-client==0.19.0
protobuf==4.25.0
psutil==5.9.6
pyarrow==14.0.1
pyarrow-hotfix==0.6
pydantic==1.10.13
pydeck==0.8.1b0
Pygments==2.16.1
pyparsing==3.1.1
pyproject_hooks==1.0.0
python-dateutil==2.8.2
python-dotenv==1.0.0
python-json-logger==2.0.7
python-multipart==0.0.6
pytz==2023.3.post1
PyYAML==6.0.1
pyzmq==25.1.1
quantile-python==1.1
ray==2.8.1
referencing==0.30.2
regex==2023.10.3
requests==2.31.0
rich==13.6.0
rpds-py==0.12.0
safetensors==0.4.0
schema==0.7.5
scipy==1.10.1
sentencepiece==0.1.99
simple-di==0.1.5
six==1.16.0
smmap==5.0.1
sniffio==1.3.0
starlette==0.27.0
streamlit==1.28.1
sympy==1.12
tenacity==8.2.3
tokenizers==0.14.1
toml==0.10.2
tomli==2.0.1
toolz==0.12.0
torch==2.1.1
tornado==6.3.3
tqdm==4.66.1
transformers==4.34.0
transformers-stream-generator==0.0.4
triton==2.1.0
typing_extensions==4.8.0
tzdata==2023.3
tzlocal==5.2
urllib3==2.0.7
uvicorn==0.24.0.post1
uvloop==0.19.0
validators==0.22.0
virtualenv==20.25.0
vllm==0.2.3
watchdog==3.0.0
watchfiles==0.21.0
websockets==12.0
wrapt==1.16.0
xformers==0.0.22.post7
xxhash==3.4.1
yarl==1.9.3
zipp==3.17.0

**Comment by aarnphm** [comment]
try
```python
TRUST_REMOTE_CODE=True openllm start baichuan-inc/Baichuan2-13B-Chat --backend vllm
```

**Comment by jim1997** [comment]
> try
> 
> ```python
> TRUST_REMOTE_CODE=True openllm start baichuan-inc/Baichuan2-13B-Chat --backend vllm
> ```

I reviewed my model and realized I'm actually using the 4-bit quantized version of Baichuan2-13B-Chat, which is Baichuan2-13B-Chat-4bits (https://huggingface.co/baichuan-inc/Baichuan2-13B-Chat-4bits). I apologize for the confusion; the error remains the same.
```shell
root@a8ee5a6d1333:/Baichuan2-13B# TRUST_REMOTE_CODE=True openllm start baichuan-inc/Baichuan2-13B-Chat-4bits --backend vllm
Given model is a local model, OpenLLM will load model into memory for serialisation.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/openllm/_llm.py", line 198, in __init__
    model = bentoml.models.get(self.tag)
  File "/usr/local/lib/python3.8/dist-packages/simple_di/__init__.py", line 139, in _
    return func(*_inject_args(bind.args), **_inject_kwargs(bind.kwargs))
  File "/usr/local/lib/python3.8/dist-packages/bentoml/models.py", line 45, in get
    return _model_store.get(tag)
  File "/usr/local/lib/python3.8/dist-packages/bentoml/_internal/store.py", line 158, in get
    raise NotFound(
bentoml.exceptions.NotFound: Model 'vllm-baichuan2-13b-chat-4bits:d8312ff4e0a1e3c24a9864265abfaf4250d8ba39' is not found in BentoML store <osfs '/root/bentoml/models'>, you may need to run `bentoml models pull` first

```
Does Openllm support Baichuan2-13B-Chat-4bits?
