### ISSUE TITLE
running openllm start opt or falcon for the first time fails

### ISSUE THREAD

**Issue by heyili** [bentoml/OpenLLM#780]
### Describe the bug

Hello I am trying to run the default opt model 

when I try to run `openllm start facebook/opt-1.3b `

I get the following error: 
`File "/Users/anaconda3/envs/ol/lib/python3.11/site-packages/openllm/_service.py", line 8, in <module>
llm = openllm.LLM[t.Any, t.Any](
^^^^^^^^^^^
AttributeError: module 'openllm' has no attribute 'LLM'`

I tried to run another model `openllm start tiiuae/falcon-7b` and get the same error 

### To reproduce

1.Install openllm (pip install openllm)
2.run openllm start opt

### Environment

Macbook Pro M1
Conda
Python 3.11.3

**Comment by aarnphm** [comment]
Ok I did not realize that someone publish openllm to conda https://anaconda.org/selfexplainml/openllm

please don;t use conda and use virtualenv instead.

**Comment by heyili** [comment]
Hey thanks for the tip but I use virtualenv instead and get the exact same error like before. 

`File "/Users/Desktop/test/ol/lib/python3.11/site-packages/openllm/_service.py", line 8, in <module>
llm = openllm.LLM[t.Any, t.Any](
^^^^^^^^^^^
AttributeError: module 'openllm' has no attribute 'LLM'`

**Comment by aarnphm** [comment]
What version of openllm is this?

**Comment by mahimairaja** [comment]
Probably you need to downgrade the version @heyili

**Comment by heyili** [comment]
I am using openllm 0.4.39. Which version would u suggest ?

**Comment by heyili** [comment]
I tried all the versions from 0.4.39 down to 0.4.30 for all versions I get:

```
llm = openllm.LLM[t.Any, t.Any](
^^^^^^^^^^^
AttributeError: module 'openllm' has no attribute 'LLM'
```

**Comment by aarnphm** [comment]
Can you do a `pip uninstall -y openllm openllm-client openllm-core && pip install -U openllm`

**Comment by heyili** [comment]
I run `pip uninstall -y openllm openllm-client openllm-core && pip install -U openllm` successfully 

then try to run `openllm start opt ` again 

still get error 

```
llm = openllm.LLM[t.Any, t.Any](
^^^^^^^^^^^
AttributeError: module 'openllm' has no attribute 'LLM'
```

**Comment by aarnphm** [comment]
What python version are you using?

**Comment by heyili** [comment]
I am using Python 3.11
```
openllm, 0.4.40 (compiled: False)
Python (CPython) 3.11.0
```

**Comment by heyili** [comment]
Hey I found the error, I have a file in the project called openllm.py. Now it is running

**Comment by aarnphm** [comment]
@heyili good to know about how python loads module https://docs.python.org/3/library/sys_path_init.html
