### ISSUE TITLE
how to stop generation stream?

### ISSUE THREAD

**Issue by mkaskov** [bentoml/OpenLLM#801]
Is there any way to stop generation stream on the model-side if it's no longer needed? For example, the client disconnected or pressed stop.

**Comment by aarnphm** [comment]
You can pass in `stop` argument on request for the token to be stopped.

**Comment by mkaskov** [comment]
I'm talking about a situation where the stream is already generating and the client disconnects or presses stop button.

**Comment by aarnphm** [comment]
not sure if I understand this, but if the client disconnects, with vLLM backend the request will be cancelled.
