### ISSUE TITLE
running out of memory

### ISSUE THREAD

**Issue by andysingal** [bentoml/OpenLLM#839]
### Describe the bug

running out of memory on Runpod 
```
pip install "openllm[vllm]" llama-index

TRUST_REMOTE_CODE=True openllm start microsoft/phi-2 --quantize int8

from llama_index import VectorStoreIndex, SimpleDirectoryReader, ServiceContext
from llama_index.llms.openllm import OpenLLM
from llama_index.text_splitter import SentenceSplitter

from llama_index.llama_dataset import download_llama_dataset

rag_dataset, documents = download_llama_dataset(
  "PaulGrahamEssayDataset", "./data"
)

llm = OpenLLMAPI(address="http://localhost:3000")

# Break down the document into manageable chunks (each of size 1024 characters, with a 20-character overlap)
text_splitter = SentenceSplitter(chunk_size=1024, chunk_overlap=20)

# Create a ServiceContext with the custom model and all the configurations
service_context = ServiceContext.from_defaults(
    llm=llm,
    embed_model="local",
    text_splitter=text_splitter,
    context_window=8192,
    num_output=4096,
)

# Build an index over the documents using the customized LLM in the ServiceContext
index = VectorStoreIndex.from_documents(documents, service_context=service_context,,vector_store_kwargs={"deep memory": True})

# Query your data using the built index
query_engine = index.as_query_engine()
response = query_engine.query("Who is Paul Graham?")
print(response)
```

### To reproduce

```
```
pip install "openllm[vllm]" llama-index

TRUST_REMOTE_CODE=True openllm start microsoft/phi-2 --quantize int8

from llama_index import VectorStoreIndex, SimpleDirectoryReader, ServiceContext
from llama_index.llms.openllm import OpenLLM
from llama_index.text_splitter import SentenceSplitter

from llama_index.llama_dataset import download_llama_dataset

rag_dataset, documents = download_llama_dataset(
  "PaulGrahamEssayDataset", "./data"
)

llm = OpenLLMAPI(address="http://localhost:3000")

# Break down the document into manageable chunks (each of size 1024 characters, with a 20-character overlap)
text_splitter = SentenceSplitter(chunk_size=1024, chunk_overlap=20)

# Create a ServiceContext with the custom model and all the configurations
service_context = ServiceContext.from_defaults(
    llm=llm,
    embed_model="local",
    text_splitter=text_splitter,
    context_window=8192,
    num_output=4096,
)

# Build an index over the documents using the customized LLM in the ServiceContext
index = VectorStoreIndex.from_documents(documents, service_context=service_context,,vector_store_kwargs={"deep memory": True})

# Query your data using the built index
query_engine = index.as_query_engine()
response = query_engine.query("Who is Paul Graham?")
print(response)
```
ERROR:
```

### Environment

```
Copy-and-paste the text below in your GitHub issue and FILL OUT the two last points.

- `transformers` version: 4.36.2
- Platform: Linux-5.4.0-165-generic-x86_64-with-glibc2.35
- Python version: 3.10.12
- Huggingface_hub version: 0.20.2
- Safetensors version: 0.4.1
- Accelerate version: 0.25.0
- Accelerate config:    not found
- PyTorch version (GPU?): 2.1.2+cu121 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>

```

**Comment by bojiang** [comment]
close for openllm 0.6
