### ISSUE TITLE
Unable to fetch models.

### ISSUE THREAD

**Issue by shersoni610** [bentoml/OpenLLM#860]
### Describe the bug

Hello,  
It seems for all the models, I get similar response: 

File "/media/M2Disk/Projects/OpenLLM/ollmenv/lib/python3.11/site-packages/openllm/serialisation/transformers/weights.py", line 30, in ModelInfo
    raise Error(f'Failed to fetch {model_id} from huggingface.co') from err
openllm_core.exceptions.Error: Failed to fetch opt-1.3b from huggingface.co

### To reproduce

I am running the code on the latest Ubuntu with Nvidia Card 4070

### Environment

Python 3.11

### System information (Optional)

Linux, Nvidia card 12 GB.

**Comment by bojiang** [comment]
close for openllm 0.6
