### ISSUE TITLE
How to update the prompt template without change openllm-core config

### ISSUE THREAD

**Issue by hahmad2008** [bentoml/OpenLLM#895]
### Describe the bug

I need to change the system message of the prompt template for one of the models in openllm, I see that we have this doc to be followed: https://github.com/bentoml/OpenLLM/blob/main/ADDING_NEW_MODEL.md

however I need to update it from openllm command as I installed openllm from pip install not from a local rep.

Could you please help me? or let me know how to install openllm from a local repo?

Thanks

### Environment

-

**Comment by bojiang** [comment]
close for openllm 0.6
