### ISSUE TITLE
feat: support Qwen1.5

### ISSUE THREAD

**Issue by sudazzk** [bentoml/OpenLLM#948]
### Feature request

https://github.com/QwenLM/Qwen1.5
https://huggingface.co/collections/Qwen/qwen15-65c0a2f577b1ecb76d786524

**Comment by yufeng1684** [comment]
You can refer to configuration_qwen.py and write a configuration file that is proven to work through personal testing. And also need to modify configuration_auto.py

**Comment by bojiang** [comment]
qwen2 supported in openllm 0.6. Pls try it!
