### ISSUE TITLE
feat: support LMDeploy backend

### ISSUE THREAD

**Issue by zhyncs** [bentoml/OpenLLM#966]
### Feature request

@aarnphm  @ssheng @parano  Hi OpenLLM team, thank you for your exceptional work. Currently, OpenLLM supports two backends, vLLM and PyTorch, with good usability but there is still room for improvement in terms of performance. [LMDeploy](https://github.com/InternLM/lmdeploy) has achieved a good balance between performance and usability, with recent Llama3 8B showing a [1.8x performance](https://mp.weixin.qq.com/s/b0MDMIfBjI1ptM8Lg2x7Vg) improvement over vLLM on LMDeploy. Performance is **crucial**, especially when the demand for large-scale deployment arises after meeting user requirements. Currently, Meituan is widely using internally. I strongly recommend OpenLLM to consider integrating LMDeploy and making it the default backend. You can refer to the documentation at https://lmdeploy.readthedocs.io/en/latest/ during the research and integration process. Thanks.

**Comment by zhyncs** [comment]
cc @lvhan028 @AllentDan

**Comment by zhyncs** [comment]
remind @aarnphm @ssheng @parano

**Comment by zhyncs** [comment]
Recently, I noticed that you published a blog post https://bentoml.com/blog/benchmarking-llm-inference-backends that mentioned LMDeploy currently does not support a wide variety of models yet. And this will continue to be developed, including subsequent support for MOE models on TurboMind and decoupling model and batch. The performance advantage will also be maintained, and I also look forward to your future plans. Cheers.

**Comment by zhyncs** [comment]
Due to the lack of response for a long time, this issue is being closed.

**Comment by bojiang** [comment]
Since vllm 0.6, this should be simple to implement. Just contribute bentos / templates to https://github.com/bentoml/openllm-models

**Comment by zhyncs** [comment]
@bojiang @aarnphm Take the liberty to find out what are the differences and advantages between OpenLLM and [Skypilot](https://github.com/skypilot-org/skypilot). Thanks.

**Comment by bojiang** [comment]
IMO Skypilot has different design pattern. It tries to do everything for users, and openllm just focus on a smaller scope.
